### ISSUE TITLE
Reflect the recent changes in Qucs-S 0.0.23

### ISSUE THREAD

**Issue by ra3xdh** [ra3xdh/qucs_s-help#1]
The following things need to be done on the documentation:

- [ ] Provide proper tutorial and correct Chapter 1 https://github.com/ra3xdh/qucs_s/issues/78
- [ ] Document changed HB variables notation https://github.com/ra3xdh/qucs_s/issues/28
- [ ] Document Xyce S-parameter simulation https://github.com/ra3xdh/qucs_s/issues/79
- [ ] Document upcoming Ngspice S-parameter simulation https://github.com/ra3xdh/qucs_s/issues/84
